#############################################################################
# Generated by PAGE version 4.23
#  in conjunction with Tcl version 8.6
#  May 20, 2019 06:01:06 PM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1073x633+536+116
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1030
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men47" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} \
        -font {"-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"} \
        -foreground {#000000} -label {trade capture} 
    menu $site_3_0.men47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men47" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} \
        -font {"-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"} \
        -foreground {#000000} -label {trade capture} -menu "$site_3_0.men48" \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} \
        -font {"-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"} \
        -foreground {#000000} -label marketData 
    menu $site_3_0.men48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {trade ID} 
    vTcl:DefineAlias "$top.lab44" "tradeIdLabel" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "tradeIdEntry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text price 
    vTcl:DefineAlias "$top.but46" "price" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex50 \
        -background white -font {-family {Segoe UI} -size 9} \
        -foreground black -height 124 -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 194 \
        -wrap word 
    .top42.tex50 configure -font "-family {Segoe UI} -size 9"
    .top42.tex50 insert end text
    vTcl:DefineAlias "$top.tex50" "output" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo43 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo43" "TradeIdCombo" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 20 -y 20 -width 92 -relwidth 0 -height 56 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 130 -y 30 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 510 -y 20 -width 106 -relwidth 0 -height 53 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex50 \
        -in $top -x 740 -y 20 -width 194 -relwidth 0 -height 124 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo43 \
        -in $top -x 140 -y 90 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

